#!/usr/bin/env bash
# Vendor the JS libraries used by the MarkdownKit rendering pipeline.
#
# All versions are pinned here. To update a library, change the version,
# re-run this script, and update MarkdownKit/JSTests/package.json to match.
# Vendored files are committed to the repo; this script is only needed when
# upgrading.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR="$ROOT/MarkdownKit/Sources/MarkdownKit/Resources/js/vendor"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

MARKDOWN_IT=14.1.0
MD_ANCHOR=9.2.0
MD_FRONT_MATTER=0.2.3
MD_FOOTNOTE=4.0.0
MD_TASK_LISTS=2.1.1
MD_KATEX=1.1.1        # @vscode/markdown-it-katex
KATEX=0.16.22
JS_YAML=4.1.0
HLJS=11.11.1          # @highlightjs/cdn-assets
MERMAID=11.12.0

echo "==> npm install (into $WORK)"
cd "$WORK"
npm init -y >/dev/null
npm install --no-audit --no-fund --silent \
  "markdown-it@$MARKDOWN_IT" \
  "markdown-it-anchor@$MD_ANCHOR" \
  "markdown-it-front-matter@$MD_FRONT_MATTER" \
  "markdown-it-footnote@$MD_FOOTNOTE" \
  "markdown-it-task-lists@$MD_TASK_LISTS" \
  "@vscode/markdown-it-katex@$MD_KATEX" \
  "katex@$KATEX" \
  "js-yaml@$JS_YAML" \
  "@highlightjs/cdn-assets@$HLJS" \
  "mermaid@$MERMAID"
NM="$WORK/node_modules"

mkdir -p "$VENDOR"

echo "==> copying UMD/IIFE builds"
cp "$NM/markdown-it/dist/markdown-it.min.js"            "$VENDOR/markdown-it.min.js"
cp "$NM/markdown-it-anchor/dist/markdownItAnchor.umd.js" "$VENDOR/markdown-it-anchor.umd.js"
cp "$NM/markdown-it-footnote/dist/markdown-it-footnote.min.js" "$VENDOR/markdown-it-footnote.min.js"
cp "$NM/markdown-it-task-lists/dist/markdown-it-task-lists.min.js" "$VENDOR/markdown-it-task-lists.min.js"
cp "$NM/katex/dist/katex.min.js"                        "$VENDOR/katex.min.js"
cp "$NM/js-yaml/dist/js-yaml.min.js"                    "$VENDOR/js-yaml.min.js"
cp "$NM/@highlightjs/cdn-assets/highlight.min.js"       "$VENDOR/highlight.min.js"
cp "$NM/mermaid/dist/mermaid.min.js"                    "$VENDOR/mermaid.min.js"

echo "==> wrapping CJS-only plugins as UMD shims"
# markdown-it-front-matter ships only CommonJS.
{
  cat <<HDR
/*! markdown-it-front-matter $MD_FRONT_MATTER — vendored, MIT. UMD shim generated by tools/vendor-js.sh. */
(function (global) {
'use strict';
var module = { exports: {} };
var exports = module.exports;
/* --- begin original source --- */
HDR
  cat "$NM/markdown-it-front-matter/index.js"
  cat <<FTR
/* --- end original source --- */
global.markdownitFrontMatter = module.exports;
})(typeof window !== 'undefined' ? window : globalThis);
FTR
} > "$VENDOR/markdown-it-front-matter.js"

# @vscode/markdown-it-katex ships TypeScript CommonJS and requires("katex").
{
  cat <<HDR
/*! @vscode/markdown-it-katex $MD_KATEX — vendored, MIT. UMD shim generated by tools/vendor-js.sh. */
(function (global) {
'use strict';
var module = { exports: {} };
var exports = module.exports;
var require = function (name) {
  if (name === 'katex') return global.katex;
  throw new Error('vendored @vscode/markdown-it-katex cannot require("' + name + '")');
};
/* --- begin original source --- */
HDR
  cat "$NM/@vscode/markdown-it-katex/dist/index.js"
  cat <<FTR
/* --- end original source --- */
global.markdownitKatex = module.exports.default || module.exports;
})(typeof window !== 'undefined' ? window : globalThis);
FTR
} > "$VENDOR/markdown-it-katex.js"

echo "==> KaTeX CSS with woff2 fonts inlined as data: URLs"
node - "$NM/katex/dist" "$VENDOR/katex.css" <<'NODE'
const fs = require('fs');
const [srcDir, outPath] = process.argv.slice(2);
let css = fs.readFileSync(`${srcDir}/katex.min.css`, 'utf8');
css = css.replace(/url\((fonts\/[^)]+\.woff2)\)/g, (_, rel) => {
  const b64 = fs.readFileSync(`${srcDir}/${rel}`).toString('base64');
  return `url(data:font/woff2;base64,${b64})`;
});
// Drop non-woff2 fallback sources; browsers all support woff2 and the data:
// URL variant is what makes fonts work inside the sandboxed Quick Look reply.
css = css.replace(/,url\(fonts\/[^)]+\) format\("(woff|truetype)"\)/g, '');
fs.writeFileSync(outPath, css);
NODE

echo "==> done: $VENDOR"
ls -la "$VENDOR"
